/* eslint-disable @typescript-eslint/no-empty-interface */
// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
// The bindings below keep TypeScript happy when the Webflow bundler type-checks
// the entire project (including API routes).
interface Env {
  DB: D1Database;
  MEDIA_BUCKET: R2Bucket;
  KV: KVNamespace;
}
